[package]
name = "flathub-cli"
version = "0.1.0"
edition = "2021"
description = "Command line interface for Flathub"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.5", features = [ "derive" ] }
